[theme]
name = "slick"

  [[block]]
  block = "networkmanager"
  on_click = "foot -e nmtui"
  interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
  interface_name_include = []
  ap_format = "{ssid^10}"

#  [[block]]
#  block = "custom"
#  command = "echo Net: `cat /sys/class/net/en*/operstate`"
#  
#   [[block]]
#   block = "custom"
#   command = "echo Wifi: `cat /sys/class/net/wl*/operstate`"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "temperature"
interval = 2
collapsed = false
scale = "celsius"
format = "{average} avg, {max} max"


[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

#<Down>[[block]]
#block = "battery"
#interval = 5
#if_command = "test -e /sys/class/power_supply/BAT0"


