[theme]
theme = "slick"
#[icons]
#icons = "awesome6"

[theme.overrides]
# Example: redefine `idle` colors
idle_bg = "#123456"
idle_fg = "#abcdef"

#[[block]]
#block = "net"
#on_click = "foot -e nmtui"
#interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
#interface_name_include = []
#ap_format = "{ssid^10}"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "



#  [[block]]
#  block = "custom"
#  command = "echo Net: `cat /sys/class/net/en*/operstate`"
#  
#   [[block]]
#   block = "custom"
#   command = "echo Wifi: `cat /sys/class/net/wl*/operstate`"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "





#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{mem_used_percents}"
#format_swap = "{swap_used_percents}"
#
[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90




[[block]]
block = "cpu"
interval = 1

#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

#[[block]]
#block = "sound"


#[[block]]
#block = "temperature"
#interval = 2
#collapsed = false
#scale = "celsius"
#format = "{average} avg, {max} max"
[[block]]
#block = "temperature"
#format = " $icon $average avg "
#format_alt = " $icon $min min, $max max, $average avg "
##format = " $icon $min min, $max max, $average avg "
interval = 2
#chip = "*-isa-*"
block = "custom"
command = "sensors | grep temp1| cut -c14-23"
#command = ''' cat /sys/class/thermal/thermal_zone0/temp | awk '{printf("%.1f\n",$1/1000)}' '''




[[block]]
block = "time"
interval = 60
[block.format]
#full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:fr_BE) "
short = " $icon $timestamp.datetime(f:%R) "

#<Down>[[block]]
#block = "battery"
#interval = 5
#if_command = "test -e /sys/class/power_supply/BAT0"

