[font]
size = 13

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"


#[font.primary]
#background = "#1D1E2BD"
#background = "#241F31"
#foreground = "[98]White"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
#gtk_theme_variant = "None"
opacity = 0.75
title = "Terminal"
#dimensions=


[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 75
lines = 25

[colors.primary]
background = '#24283b'
foreground = '#a9b1d6'
dim_foreground = "#828482"  
bright_foreground = "None"  


#[colors.normal]
#      black =   '#32344a'
#      red =     '#f7768e'
#      green =   '#9ece6a'
#      yellow =  '#e0af68'
#      blue =    '#7aa2f7'
#      magenta = '#ad8ee6'
#      cyan =    '#449dab'
#      white =   '#9699a8'
#
#
#[colors.bright]
#
#      black =   '#444b6a'
#      red =     '#ff7a93'
#      green =   '#b9f27c'
#      yellow =  '#ff9e64'
#      blue =    '#7da6ff'
#      magenta = '#bb9af7'
#      cyan =    '#0db9d7'
#      white =   '#acb0d0'
